cargo-features = ["edition2021"]
[package]
name = "rust-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
crossbeam = "*"
serde = "*"
nonzero_ext = "*"
reqwest = { version = "*", features = ["serde_json", "json"] }
governor = "*"
rayon = "*"
#tungstenite = "*" # included in async-tungstenite
async-tungstenite = { version = "*", features = ["tokio-rustls"] }
anyhow = "*"
async-compat = "*"
futures = "*"
tracing = "*"
tracing-log = "*"
tracing-subscriber = "*"
log-panics = "*"
pin-utils = "*"

[features]
enable_logging = []