[package]
name = "rust-examples"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "*"
tokio = { version = "1", features = ["full"] }
crossbeam = "*"
serde = "*"
nonzero_ext = "*"
paperplane = "*"
reqwest = { version = "*", features = ["serde_json", "json"] }
governor = "*"
rayon = "*"

